### ISSUE TITLE
cock

### ISSUE THREAD

**Issue by SamyoFox** [xAndrei166/mods#1]
the z

- [x] i like cock

**Comment by ad2017gd** [comment]
MILSUGI!!!!!!!!!!1

**Comment by SamyoFox** [comment]
ALUPIGUS

**Comment by ad2017gd** [comment]
TACI IN PULA MEA SAMUOCORD

**Comment by SamyoFox** [comment]
![marisus](https://user-images.githubusercontent.com/44713424/107222577-68339300-6a15-11eb-9b51-1d7f2bf4b4cf.png)

**Comment by wolfemium** [comment]
SAMYO MILSUGI!@!!!!!!!!!!!!!!!!!!@!@@!

**Comment by ad2017gd** [comment]
NU IMI PASA C!!!!!!!!!!!!!!!!!**3DSFSDF**

- SDSDFSDF

1.  @_**
![1d]
![classickot](https://user-images.githubusercontent.com/39013925/107222707-ec8a1400-6a1d-11eb-8795-6455d42c3bfd.png)

**_

**Comment by ad2017gd** [comment]
__

**Comment by SamyoFox** [comment]
![800662968530108426](https://user-images.githubusercontent.com/44713424/107222899-c791a300-6a15-11eb-9930-f613e875f378.png)

**Comment by wolfemium** [comment]
ad what the fuck happened
did you break your mouse jacking off to bread cat pussy

**Comment by ad2017gd** [comment]
Va rog sa nu ma confundati cu dvs. bagamias pualn mata de lup frecat

**Comment by wolfemium** [comment]
nu sunt lup frecat
sunt un lep care a frecat-o pe ma-ta 🤣

**Comment by ad2017gd** [comment]
e clar Mil sugi cu pofta futi i nmorit mait

**Comment by wolfemium** [comment]
in visele tale

**Comment by Cristy86** [comment]
no

**Comment by iiisak** [comment]
am intrebat?

**Comment by Cristy86** [comment]
this is still open loser andrei!

**Comment by zCri** [comment]
encezo plm mil sugi rau tu si familia ta de prosti

**Comment by ghost** [comment]
i didn't say anything bro, check comments

**Comment by ghost** [comment]
[![zcriedge](https://forthebadge.com/images/badges/ctrl-c-ctrl-v.svg)](https://forthebadge.com)

**Comment by ad2017gd** [comment]
Voi redeschide aceasta problema.

**Comment by ad2017gd** [comment]
Mam razgandit

**Comment by ad2017gd** [comment]
Date drauc

**Comment by ghost** [comment]
fuck u!

**Comment by ad2017gd** [comment]
Sa ma sughi cristi

**Comment by ghost** [comment]
> 
> 
> Sa ma sughi cristi

sorry but your mother is doing it right now as we speak

**Comment by ad2017gd** [comment]
![pasc0](https://user-images.githubusercontent.com/39013925/107333465-31658780-6abe-11eb-9f8e-f4062e8dfaff.gif)

**Comment by ghost** [comment]
> ![pasc0](https://user-images.githubusercontent.com/39013925/107333465-31658780-6abe-11eb-9f8e-f4062e8dfaff.gif)

oooooh. this u or your brother?
[![forthebadge](https://forthebadge.com/images/badges/you-didnt-ask-for-this.svg)](https://forthebadge.com)

**Comment by zCri** [comment]
taci dreq voi imi trimiteti spam email

**Comment by ghost** [comment]
> taci dreq voi imi trimiteti spam email


stai acolo si mananca sarmale

**Comment by ad2017gd** [comment]
zcri mio trimit pe mata rpin Mail

**Comment by ghost** [comment]
@ad2017gd vezi ca ai rachete la comment-ul tau!!

**Comment by zCri** [comment]
am mama ta la comment-ul meu !!! 🤣

**Comment by ghost** [comment]
> am mama ta la comment-ul meu !!! 🤣

2/65. COMPREHENSION Read the dialogue again and choose the correct answer.

| 1 Mrs Martin thinks Scotland is
    A  sad. ❌
    B  beautiful. ✔️
    C  cold. ❌

**Comment by ad2017gd** [comment]
Mrs martin Crede ca trebuie sa Faci

**Comment by ad2017gd** [comment]
u9

**Comment by iiisak** [comment]
Scotland is sad smh

**Comment by AirDog46** [comment]
sex 69
