### ISSUE TITLE
readme.md

### ISSUE THREAD

**Issue by Cristy86** [xAndrei166/mods#2]
[![forthebadge](https://forthebadge.com/images/badges/made-with-crayons.svg)](https://forthebadge.com)

**Comment by Cristy86** [comment]
[![sus](https://forthebadge.com/images/badges/built-with-grammas-recipe.svg)](https://forthebadge.com)

**Comment by Cristy86** [comment]
[![creepi942](https://forthebadge.com/images/badges/you-didnt-ask-for-this.svg)](https://forthebadge.com)

**Comment by xAndrei166** [comment]
tf do you want

**Comment by Cristy86** [comment]
u can't just close it, FIX README.MD
u bananahead

**Comment by xAndrei166** [comment]
what the fuck do you want go away

**Comment by xAndrei166** [comment]
What's wrong with readme.md

**Comment by Cristy86** [comment]
sus

**Comment by Cristy86** [comment]
sus
