### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by iiisak** [xAndrei166/mods#3]
add readme.md

**Comment by iiisak** [comment]
stop scielcencing the pupopl

**Comment by xAndrei166** [comment]
there is a readme.md

**Comment by iiisak** [comment]
proof?

**Comment by xAndrei166** [comment]
![Screenshot_20210208-233948](https://user-images.githubusercontent.com/31206758/107284876-0f8ce600-6a67-11eb-9b71-92e08d64bd7d.png)

**Comment by iiisak** [comment]
Photoshopped!

**Comment by SamyoFox** [comment]
https://github.com/xAndrei166/mods/blob/main/README.md

**Comment by xAndrei166** [comment]
time to silence the community
